apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: production-model
  namespace: dognauts-sup
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: model
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://dognauts-sup/1/8747055ef330491c9aae0d400e5b5c3b/artifacts/model
      name: model
    name: model
    replicas: 1
